import { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import { RiAddLine, RiDeleteBinLine, RiEdit2Line } from 'react-icons/ri';
import Button from '../../components/ui/Button';
import Table from '../../components/ui/Table';
import ExpenseForm from './ExpenseForm';
import { listExpenses, deleteExpense } from '../../services/expenseService';

const ExpenseList = () => {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingExpense, setEditingExpense] = useState(null);

  const loadData = async () => {
    try {
      setLoading(true);
      const res = await listExpenses({ limit: 50 });
      setData(res.data || []);
    } catch (error) {
      toast.error('Failed to load expenses');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleEdit = (expense) => {
    if (expense.entity_type) {
      toast('Note: This is an auto-generated expense. It is recommended to edit the original document instead.', { icon: '⚠️' });
    }
    setEditingExpense(expense);
    setIsFormOpen(true);
  };

  const handleDelete = async (id, isAuto) => {
    if (isAuto) {
      if (!window.confirm('WARNING: This expense was auto-generated by another module. Are you sure you want to delete it standalone?')) return;
    } else {
      if (!window.confirm('Are you sure you want to delete this expense?')) return;
    }
    
    try {
      await deleteExpense(id);
      toast.success('Expense deleted');
      loadData();
    } catch (error) {
      toast.error(error.message);
    }
  };

  const columns = [
    { 
      header: 'Date', 
      accessor: 'expense_date',
      cell: (row) => new Date(row.expense_date).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })
    },
    { header: 'Category', accessor: 'category' },
    { 
      header: 'Description', 
      accessor: 'description',
      cell: (row) => (
        <div>
          {row.description}
          {row.entity_type && <span style={{ fontSize: '0.75rem', marginLeft: '0.5rem', background: 'var(--color-surface)', padding: '2px 6px', borderRadius: '4px', border: '1px solid var(--color-border)' }}>Auto</span>}
        </div>
      )
    },
    { header: 'Payment', accessor: 'payment_type' },
    { 
      header: 'Amount (₹)', 
      accessor: 'amount', 
      align: 'right',
      cell: (row) => <strong style={{color: 'var(--color-error)'}}>₹{parseFloat(row.amount).toFixed(2)}</strong>
    },
    {
      header: 'Actions',
      align: 'right',
      cell: (row) => (
        <div className="table-actions">
          <button
            onClick={() => handleEdit(row)}
            className="icon-action-btn"
            aria-label="Edit expense"
            title="Edit"
          >
            <RiEdit2Line size={18} />
          </button>
          <button
            onClick={() => handleDelete(row.id, !!row.entity_type)}
            className="icon-action-btn icon-action-btn--danger"
            aria-label="Delete expense"
            title="Delete"
          >
            <RiDeleteBinLine size={18} />
          </button>
        </div>
      )
    }
  ];

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">Expenses</h1>
        <Button variant="primary" onClick={() => { setEditingExpense(null); setIsFormOpen(true); }}>
          <RiAddLine size={20} />
          New Expense
        </Button>
      </div>

      {loading ? (
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Loading expenses...</p>
        </div>
      ) : (
        <Table columns={columns} data={data} keyField="id" />
      )}

      {isFormOpen && (
        <ExpenseForm 
          isOpen={isFormOpen} 
          onClose={() => setIsFormOpen(false)} 
          expense={editingExpense}
          onSuccess={loadData}
        />
      )}
    </div>
  );
};

export default ExpenseList;
